apiVersion: apps/v1
kind: Deployment
metadata:
  name: crimeapi-deployment
  labels:
    app: crimeapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crimeapi
  template:
    metadata:
      labels:
        app: crimeapi 
    spec:
      containers:
        - name: crimeapi 
          image: repcrimeacr.azurecr.io/crimeapi
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
    name: crimeapi-service  
spec:
    type: LoadBalancer
    selector:
      app: crimeapi
    ports:
      - protocol: TCP
        port: 80