apiVersion : apps/v1
kind: Deployment
metadata:
  name: crimeapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crimeapi
  template:
    metadata:
      labels:
        app: crimeapi 
    spec:
      containers:
        - name: crimeapi 
          image: repcrimeacr.azurecr.io/crimeapi
          ports:
          - containerPort: 80