version: '3.4'

services:
  msqlsrv:
    ports:
      - "13433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "_Password123"
      MSSQL_PID: Express

  crime.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://rep-crime:x9Ly8QcymEylDql38xmLyaPrU9dd5mKHsgpXiFAtcEZleMCg9wFFzukn8sdcw3Yxz25sU18boBug8BSA1oydvQ==@rep-crime.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@rep-crime@"
    ports:
      - "13000:80"

  lawenforcement.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "13001:80"