version: '3.4'

services:
  mongosrv2:
    image: mongo

  msqlsrv:
    container_name: msqlsrv
    image: mcr.microsoft.com/mssql/server:2019-CU11-ubuntu-20.04

  crime.api:
    image: ${DOCKER_REGISTRY-}crimeapi
    build:
      context: .
      dockerfile: Crime.API/Dockerfile

  lawenforcement.api:
    image: ${DOCKER_REGISTRY-}lawenforcementapi
    build:
      context: .
      dockerfile: LawEnforcement.API/Dockerfile

